### ISSUE TITLE
reset and restart button

### ISSUE THREAD

**Issue by piyushbaibhav** [piyushbaibhav/TypoTester#3]
When the restart or reset button is clicked the speed doesn't reset it just continues from its previous values.

**Comment by ishanksainger** [comment]
I can work on this

**Comment by piyushbaibhav** [comment]
hey there @ishanksainger, may I know how you came across this repo?

**Comment by ishanksainger** [comment]
@piyushbaibhav I was trying to search repos to contribute so searched issues which are good first issues and found yours

**Comment by ishanksainger** [comment]
@piyushbaibhav hey! As i can when u click on retry or restart it goes back to 0 on speed and accuracy and time goes back to selected time. I guess, this is what you wanted?

**Comment by piyushbaibhav** [comment]
@ishanksainger  See whenever the user clicks the restart or reset button speed, accuracy and time should go back to 0 which it does. But In the case of speed, at the first try it is correct but when restart or rest is clicked instead of starting from the beginning it continues from the previous test values.
![Screenshot 2023-12-12 172935](https://github.com/piyushbaibhav/TypoTester/assets/98445212/cdfdf31b-62b4-4424-97f8-27a4c3127c77)
here you can see at 12 sec the speed is 20 wpm but when I reset and then start over instead of speed being close to 20 wpm it just continues from 20 wpm to lower values.
![Screenshot 2023-12-12 172947](https://github.com/piyushbaibhav/TypoTester/assets/98445212/f9e1cb84-1047-42bc-9307-e3b5d1e57b0c)
as you can see on the above ss.
I think there is some problem with ` const minutes = timeElapsed / 60;` in the timer component not being updated when the restart or reset button is clicked, I'm not sure though I couldn't figure it out.

**Comment by ishanksainger** [comment]
By reset you mean retry or restart? Because I have tried multiple times and every time i hit retry or restart speed and accuracy becomes 0 and if i try again to write it starts from 0, also if I complete the timer then it shows completed in the input box

**Comment by piyushbaibhav** [comment]
I meant retry. Han jab bhi retry aur restart button dbane pe sab kuch 0 hojana chaiye vo to correct hai but problem ye hai ki reset dbane ke baad when you start typing again tab jo speed ki calculations hai vo galat ho jati hai. ss me jesa dikh rha hai ki pehle 12 sec me speed sahi hai joki 20WPM but in 2nd ss you can see that 12 sec me hi 5 WPM speed show kr rha hai jo ki wrong hai.

**Comment by piyushbaibhav** [comment]
you understand Hindi right? @ishanksainger

**Comment by ishanksainger** [comment]
Yes

**Comment by ishanksainger** [comment]
Ok thanks for explaining, got the point and tested as well. Will check and get back to you

**Comment by piyushbaibhav** [comment]
hey @ishanksainger while reviewing your code I came across another bug related to this. So jo original issue tha speed ka vo related to restart or reset button that jo ki fix hoggya but yhi same issue ab mode select ke sath ho rha hai. Whenever user changes the mode sab kuch 0 ho jata hai but speed pichle wale values see hi continue krta hai.

Please let me know if you would like to fix this issue or not. If yes, I could open a new issue for this and assign you that.

you can create a pull request for your previous code, I'll be happy to merge that.

**Comment by ishanksainger** [comment]
Sure will create a PR for this and yes will work on the other issue as well.
